# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:

  sqldbase:
    container_name: sql_dbase
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Supersecret@2022"
      ACCEPT_EULA: "Y"
    networks:
      - bookstorenetwork

  bookstoreapi:
    container_name: bookstoreapi_container
    image: bookstoreapi_image
    build:
      context: .
      dockerfile: src/Bookstore.Api/Dockerfile
    ports:
      - 44337:44337
    volumes:
      - bookstoredata:/BookstoreStorage
    depends_on:
      - sqldbase
    networks:
      - bookstorenetwork

  bookstorclient:
    container_name: bookstoreclient_container
    image: bookstoreclient_image
    build:
      context: .
      dockerfile: src/Bookstore.Client/Dockerfile
    ports:
      - 7174:7174
    depends_on:
      - bookstoreapi
    networks:
      - bookstorenetwork


networks:
  bookstorenetwork:
    driver: bridge

volumes:
  bookstoredata: