# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  bookstoreapi:
    image: bookstoreapi
    build:
      context: .
      dockerfile: src/Bookstore.Api/Dockerfile
    ports:
      - 44336:44336
    depends_on:
      - sqlserver

  sqlserver:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"