POST https://localhost:7257/api/bookstore
Content-Type: application/json

{
    "title" : "title",
    "author" : "Sarwa",
    "description" : "title2 description",
    "CoverImageUrl" : "cover image url",
    "BookUrl" : "book url",
    "publishDate" : "2022-01-11"
}