POST https://localhost:44336/api/bookstore
Content-Type: application/json

{
    "title" : "title1",
    "author" : "Sarwan",
    "description" : "title1 description",
    "CoverImageUrl" : "cover image url",
    "BookUrl" : "book url",
    "publishDate" : "2022-09-15"
}