@id=8bfb0dda-05ae-4519-a319-396ad6b4a07f

PUT https://localhost:7257/api/bookstore/{{id}}
Content-Type: application/json

{
    "title" : "title1",
    "author" : "Sarwan",
    "description" : "title2 description",
    "CoverImageUrl" : "cover image url",
    "BookUrl" : "book url",
    "publishDate" : "2022-09-11"
}